CREATE TABLE IF NOT EXISTS `civicrm_bipdata` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Default MySQL primary key',
  `bip_bbl` int(11) DEFAULT NULL,
  `address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `res_unit` int(11) DEFAULT NULL,
  `tot_unit` int(11) DEFAULT NULL,
  `num_floors` int(11) DEFAULT NULL,
  `census_tract` double DEFAULT NULL,
  `borocode` int(11) DEFAULT NULL,
  `block` int(11) DEFAULT NULL,
  `lot` int(11) DEFAULT NULL,
  `commdist` int(11) DEFAULT NULL,
  `lucategory` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `year_built` int(11) DEFAULT NULL,
  `yr_1st_alt` int(11) DEFAULT NULL,
  `yr_2nd_alt` int(11) DEFAULT NULL,
  `bldg_class` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zoning_gen` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zoning` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `open_violations` int(11) DEFAULT NULL,
  `open_a_violations` int(11) DEFAULT NULL,
  `open_b_violations` int(11) DEFAULT NULL,
  `open_c_violations` int(11) DEFAULT NULL,
  `prioryear_violations` double DEFAULT NULL,
  `prioryear_a_violations` int(11) DEFAULT NULL,
  `prioryear_b_violations` double DEFAULT NULL,
  `prioryear_c_violations` int(11) DEFAULT NULL,
  `seven_a` double DEFAULT NULL,
  `aep` int(11) DEFAULT NULL,
  `ppi` double DEFAULT NULL,
  `underlying_conditions` int(11) DEFAULT NULL,
  `nyc_421a_exempt_properties` int(11) DEFAULT NULL,
  `prioryear_311_comps` int(11) DEFAULT NULL,
  `dob_violation` int(11) DEFAULT NULL,
  `ecb_violation` int(11) DEFAULT NULL,
  `city_lien` double DEFAULT NULL,
  `water` double DEFAULT NULL,
  `umbrella` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `party_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `document_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `recorded_filed` datetime DEFAULT NULL,
  `absolute` double DEFAULT NULL,
  `per_unit` double DEFAULT NULL,
  `current_bip_score` double DEFAULT NULL,
  `score_2015april` double DEFAULT NULL,
  `score_2015jan` double DEFAULT NULL,
  `score_2014oct` double DEFAULT NULL,
  `score_2014jun` double DEFAULT NULL,
  `score_2014feb` double DEFAULT NULL,
  `score_2013nov` double DEFAULT NULL,
  `score_2013aug` double DEFAULT NULL,
  `score_2013april` double DEFAULT NULL,
  `score_2012nov` double DEFAULT NULL,
  `score_2012june` double DEFAULT NULL,
  `score_2012jan` double DEFAULT NULL,
  `score_2010_2` double DEFAULT NULL,
  `score_2010_1` double DEFAULT NULL,
  `score_2009_2` double DEFAULT NULL,
  `score_2009_1` double DEFAULT NULL,
  `score_2008_2` double DEFAULT NULL,
  `occurance` int(11) DEFAULT NULL,
  `average` double DEFAULT NULL,
  `cdfavg` double DEFAULT NULL,
  `corpname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `corpstreet` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `corpapt` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `corpcity` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `corpstate` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `indivfirstname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `indivlastname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `indivstreet` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `indivapt` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `indivcity` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `indivst` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headofftitle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headofffirstname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headofflastname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headoffstreet` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headoffcity` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headoffst` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtcorp` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtfirstname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtlastname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtstreetnum` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtstreet` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtapt` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtcity` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtst` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `violations_current_as_of` datetime DEFAULT NULL,
  `headoffapt` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `corpstreetnum` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headoffstreetnum` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `erps` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `soldliensopen` double DEFAULT NULL,
  `open_i_violations` double DEFAULT NULL,
  `prioryear_v_to_c_ratio` double DEFAULT NULL,
  `indivstreetnum` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `headoffzip` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `indivzip` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `doc_amount` double DEFAULT NULL,
  `corpzip` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mngmtzip` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip_code` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `INDEX_borocode` (`borocode`),
  KEY `INDEX_block` (`block`),
  KEY `INDEX_lot` (`lot`),
  KEY `INDEX_lucategory` (`lucategory`),
  KEY `INDEX_year_built` (`year_built`),
  KEY `INDEX_yr_1st_alt` (`yr_1st_alt`),
  KEY `INDEX_yr_2nd_alt` (`yr_2nd_alt`),
  KEY `INDEX_bldg_class` (`bldg_class`),
  KEY `INDEX_umbrella` (`umbrella`),
  KEY `INDEX_address` (`address`),
  KEY `INDEX_recorded_filed` (`recorded_filed`),
  KEY `INDEX_current_bip_score` (`current_bip_score`),
  KEY `INDEX_corpcity` (`corpcity`),
  KEY `INDEX_corpstate` (`corpstate`),
  KEY `INDEX_violations_current_as_of` (`violations_current_as_of`),
  KEY `INDEX_bip_bbl` (`bip_bbl`),
  KEY `dedupe_index_bbl` (`bip_bbl`)
) ENGINE=InnoDB AUTO_INCREMENT=57306 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
